name: build+test

on:
  push:
    branches:
      - "**"

  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for manual trigger"
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout brownie repo
        uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: download dependencies
        run: make install

      - name: audit code
        run: make audit

      - name: run unit tests
        run: make test

      - name: build artifact
        run: make build

      - name: upload binary artifact
        uses: actions/upload-artifact@master
        with:
          name: binary
          path: tmp/bin/brownie

      - name: upload test artifact
        uses: actions/upload-artifact@master
        with:
          name: test
          path: oci.sh

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout runtime-tools repo
        uses: actions/checkout@v4
        with:
          repository: nixpig/runtime-tools

      - name: install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0

      - name: install tap
        run: npm install tap

      - name: build runtime-tools
        run: make runtimetest validation-executables

      - name: download binary artifact
        uses: actions/download-artifact@master
        with:
          name: binary
          path: .

      - name: download test artifact
        uses: actions/download-artifact@master
        with:
          name: test
          path: .

      - name: chmod brownie
        run: chmod 755 ./brownie

      - name: run oci tests
        run: |
          sudo RUNTIME=./brownie bash ./oci.sh
